// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEl09iVNVqSaqvVBqNIzhul0x3mAhPLoY',
    appId: '1:204384261168:web:034da1b6cd7435e49789f5',
    messagingSenderId: '204384261168',
    projectId: 'nexus-mobile-project',
    authDomain: 'nexus-mobile-project.firebaseapp.com',
    storageBucket: 'nexus-mobile-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6YgZ1kLBiGbX73vvXnBctOD0Dk29cvE',
    appId: '1:204384261168:android:4a2eb74fa87353c19789f5',
    messagingSenderId: '204384261168',
    projectId: 'nexus-mobile-project',
    storageBucket: 'nexus-mobile-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxJa4g1-mC5GxF8s1xnfA3MGpB5daMAY',
    appId: '1:204384261168:ios:4fd54bfed932ff9a9789f5',
    messagingSenderId: '204384261168',
    projectId: 'nexus-mobile-project',
    storageBucket: 'nexus-mobile-project.firebasestorage.app',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxJa4g1-mC5GxF8s1xnfA3MGpB5daMAY',
    appId: '1:204384261168:ios:4fd54bfed932ff9a9789f5',
    messagingSenderId: '204384261168',
    projectId: 'nexus-mobile-project',
    storageBucket: 'nexus-mobile-project.firebasestorage.app',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEl09iVNVqSaqvVBqNIzhul0x3mAhPLoY',
    appId: '1:204384261168:web:b2e554226ef182739789f5',
    messagingSenderId: '204384261168',
    projectId: 'nexus-mobile-project',
    authDomain: 'nexus-mobile-project.firebaseapp.com',
    storageBucket: 'nexus-mobile-project.firebasestorage.app',
  );
}
